### ISSUE TITLE
RTL thread lines are incorrect

### ISSUE THREAD

**Issue by sharonv** [pengx17/logseq-plugin-bullet-threading#12]
RTL support needed
![image](https://user-images.githubusercontent.com/5072977/206877062-f4294561-6114-4ee2-a3c4-bc68ec2ead5f.png)

**Comment by whZhang1** [comment]
Amazingly, I update the logseq software and the issue was fixed

**Comment by nashamri** [comment]
![image](https://github.com/pengx17/logseq-plugin-bullet-threading/assets/1207107/fe711be1-12a8-4532-a687-fb5ad5eef746)

The issue is still there, using `logseq` version `0.9.8`
